combine add_node with add_nodes and add_egde with add_edges
QuantStack/ipycytoscape pull request #214
Opened 2020-12-18 13:41 UTC by sven5s

Mentioned in #195

2020-12-18 16:02 UTC, ianhi requested changes
Thanks! This is indeed a nice simplification but I'm worried that the `*args, **kwargs` argument make it harder for the user to see what's going on.

2020-12-18 16:02 UTC, ianhi commented on ipycytoscape/cytoscape.py
> +    def add_edge(self, edge, *args, **kwargs):
Since `add_edges` only has two kwargs I'd prefer to leave this as 
`def add_edge(self, edge, directed=False, multiple_edges=False):`

This makes it much more discoverable for the user what the valid kwargs are. There are cases where this makes some sense, such as in Matplotlib where they have a huge number of kwargs. But here we only have two so let's leave it explicit.

2020-12-18 16:04 UTC, ianhi commented
This doesn't need to happen here but at some point checks should be added to `add_edges` and `add_nodes` that the `node/edge` being added is actually the correct object and if not we should fail with a clear error message.

2020-12-22 12:25 UTC, marimeireles commented
Awesome change @sven5s :)
Thanks for the PR!

2021-01-04 10:30 UTC, sven5s commented on ipycytoscape/cytoscape.py
> +    def add_node(self, node, *args, **kwargs):
I thought of it like a wrapper function and so I used the typical syntax. I also don't wanted to add everything twice but I understand you opinion and changed it. Maybe we will find a better way in the future but a the moment this is good enough.

2021-01-04 10:33 UTC, sven5s commented
> 
> 
> This doesn't need to happen here but at some point checks should be added to `add_edges` and `add_nodes` that the `node/edge` being added is actually the correct object and if not we should fail with a clear error message.

This is a really good point. We should open an issue to keep track of this.

2021-01-04 16:36 UTC, ianhi approved these changes
Looks good - thanks!

2021-01-04 16:37 UTC, merged

2021-01-04 16:37 UTC, ianhi commented
@sven5s this will get picked up into the release adding jlab3 support which should be soonish