Adding example with pandas. A different approach
QuantStack/ipycytoscape pull request #231
Opened 2021-01-29 22:40 UTC by joseberlines

Hi @marimeireles, Hi @ianhi 
I PR adding a new example file that illustrates an alternative use of pandas for manipulating the graphs resulting with ipycytoscape.

When I have time and find the way it is my intention to PR the method into the source code of ipycytoscape.

2021-03-01 13:34 UTC, joseberlines commented
I just realise now there are some problems in this note book. I will have a look.

2021-03-11 19:19 UTC, joseberlines commented
I just dont understand what are the tests Falling in this file.

2021-03-12 13:46 UTC, marimeireles commented
Hey @joseberlines, sorry I'm not super present around... I'm trying to finish another review and once I do I'll get back to this PR :)
Thank you for the contributions! :cherry_blossom: It's really super appreciated, sorry for the lack of time here.

2021-03-18 16:40 UTC, marimeireles commented
Hey @joseberlines, thank you for the contribution :)
So the way our test system is working currently is: it's grabbing the notebooks we have on our example folder and running all of them. I don't know much about the internals of this, but investigating your PR further I found that this behavior is changing depending on which cells you've previously executed.

I'm going to create a contributing.md file to document some pitfalls we might get into while contributing. But one thing that fixed most bugs was actually was restarting and cleaning the notebook:

![image](https://user-images.githubusercontent.com/17600982/111656038-121af200-8802-11eb-80b9-e32735b4c6c4.png)

We should always have [ ] empty execution cells.

Now we actually have one error in the code itself:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-f1cd00616845> in <module>
----> 1 stations_df['background-color'] = stations_df['id'].apply(lambda x: 'violet' if x in list_of_HS_stations and x is not None else 'yellow')

~/miniconda3/envs/ipycytoscape/lib/python3.9/site-packages/pandas/core/series.py in apply(self, func, convert_dtype, args, **kwds)
   4136             else:
   4137                 values = self.astype(object)._values
-> 4138                 mapped = lib.map_infer(values, f, convert=convert_dtype)
   4139 
   4140         if len(mapped) and isinstance(mapped[0], Series):

pandas/_libs/lib.pyx in pandas._libs.lib.map_infer()

<ipython-input-13-f1cd00616845> in <lambda>(x)
----> 1 stations_df['background-color'] = stations_df['id'].apply(lambda x: 'violet' if x in list_of_HS_stations and x is not None else 'yellow')

TypeError: argument of type 'NoneType' is not iterable
```

I'll mark it in a review.

2021-03-18 16:45 UTC, marimeireles requested changes
Also, there are a few grammar mistakes. I'd recommend using this tool: https://www.scribens.com/ in all of the markdow cells to check :)
It's what I usually run in my texts, english is annoyingly tricky for non natives like us ;/

2021-03-18 16:45 UTC, marimeireles commented on examples/ipycytoscape_with_pandas_a_different_approach.ipynb
> +    "stations_df['background-color'] = stations_df['id'].apply(lambda x: 'violet' if x in list_of_HS_stations else 'yellow')"
Hi @joseberlines, the bug that I mentioned is happening here, in this cell :)

2021-03-18 17:12 UTC, joseberlines commented
Thanks to both. 
Indeed I did not think for a second about cleanibg the outputs. I will have a look. If you want I can tr a new PR and discjarge this one.

2021-03-19 09:46 UTC, marimeireles commented
@joseberlines you choose! :) either way is fine.

2021-03-29 12:14 UTC, closed without merging

2021-03-29 12:15 UTC, marimeireles commented
Closing because #245 contains #231