Updated version
QuantStack/ipycytoscape pull request #245
Opened 2021-03-01 07:01 UTC by pwrose

Simplified code and run black.

2021-03-04 05:17 UTC, ianhi reviewed
Hi @pwrose thanks for all the work you've been putting in on this. I've left a few comments on the code.

I'd also like to ask that you implement tests that check the various ways the new method works. I trust that it works now, but this will make it much easier to maintain the function in the future.

2021-03-04 05:17 UTC, ianhi commented on ipycytoscape/cytoscape.py
> +import neotime
I'm going to make a PR making the other graph libraries optional imports as well, but for now can you make this import lazy by putting inside the function where it gets used.

2021-03-04 05:17 UTC, ianhi commented on ipycytoscape/cytoscape.py
> +        multiple_edges = True
Are all neo4j graphs directed?

2021-03-04 05:17 UTC, ianhi commented on ipycytoscape/cytoscape.py
> +    def get_node_labels_by_priority(g):
This is pretty specific too `neo4j` so at a minimum this function will need checks that the `node` has the appropriate attribute. Or like the above it should be moved into a utils files or private helper.

2021-03-04 05:17 UTC, ianhi commented on setup.py
> +        "py2neo",
Missing `neotime`

2021-03-04 05:17 UTC, ianhi commented on setup.py
> +        "py2neo",
also I don't think you ever actually make use of `py2neo` - do we need to require this?

2021-03-06 21:46 UTC, pwrose commented on ipycytoscape/cytoscape.py
> +    def convert_neo4j_types(node_attributes):
I've made this a helper function. Users would not access this function.

2021-03-06 21:46 UTC, pwrose commented on ipycytoscape/cytoscape.py
> +    def create_tooltip(node_attributes, node_labels):
I made this a helper function.

2021-03-06 21:52 UTC, pwrose commented on ipycytoscape/cytoscape.py
> +                node_attributes["tooltip"] = tooltip_text
Yes, the other ```from___``` methods don't create a tooltip. However, Neo4j is a property graph and without a convenient way to display the properties, there isn't much value. I have a couple of suggestions on how to deal with tooltips. Should I open a new issue for a discussion on tooltips that could be applied to all ```from___```?

2021-03-06 21:53 UTC, pwrose commented on ipycytoscape/cytoscape.py
> +import neotime
I've put the neotime import in the function itself.

2021-03-06 21:53 UTC, pwrose commented on ipycytoscape/cytoscape.py
> +        multiple_edges = True
Yes, neo4j graphs are directed. I've put a comment in the code.

2021-03-06 21:55 UTC, pwrose commented on ipycytoscape/cytoscape.py
> +    def get_node_labels_by_priority(g):
All neo4j nodes have at least one label and can have multiple labels. I've made this a helper function.

2021-03-06 21:59 UTC, pwrose commented on setup.py
> +        "py2neo",
I've added neotime. ```py2neo``` is not required for ipycytoscape, but the example notebook needs it to run the notebook tests. That's the reason why ```networkx``` is also included here. Is there a way to separate the core ipycytoscape dependencies from the notebook dependencies?

2021-03-06 22:00 UTC, pwrose commented on setup.py
> +        "py2neo",
Also, should I pin down a specific version of py2neo here and in environment.yml?

2021-03-07 00:54 UTC, pwrose commented
Regarding tests, the [example notebook](https://github.com/pwrose/ipycytoscape/blob/master/examples/Neo4j_Example.ipynb) is probably the best I can come up with. The problem with testing this functionality is that a running Neo4j Graph Database is required. The example notebook connects to our COVID Neo4j database. The repo https://github.com/sbl-sdsc/neo4j-ipycytoscape runs an instance of the Neo4j database on the Pangeo binder (doesn't work on mybinder.org because of blocked ports), but that cannot be integrated with this repo.

2021-03-09 13:40 UTC, marimeireles commented on setup.py
> +        "py2neo",
Unless you're using a specific version, I don't think it's necessary.
Thank you @pwrose. I'm going to try to give a look too.
Thanks for chiming in @ianhi! :cherry_blossom:

2021-03-15 10:47 UTC, marimeireles requested changes
Awesome work @pwrose.
Thank you for this and once again sorry for taking so long to review it!

2021-03-15 10:47 UTC, marimeireles commented on ipycytoscape/cytoscape.py
> +                    counts[label] = counts.get(label, 0) + 1
Could you please add a comment explaining what this line is doing? It's a bit obscure to me.

2021-03-15 10:47 UTC, marimeireles commented on ipycytoscape/cytoscape.py
> +        def convert_neo4j_types(node_attributes):
Maybe we should use a more generic name? Like `convert_types_to_string` since there's nothing intrinsic to `neo4j` being done here, right? (Maybe others could reuse this code for some other thing)

2021-03-15 10:48 UTC, marimeireles commented
Don't worry about dealing with the conflicts if you don't want to, I can deal with them once the review is done :)

2021-03-26 11:25 UTC, marimeireles commented
I can also finish this PR if @ianhi and @pwrose are okay :)

2021-03-30 19:51 UTC, pwrose commented on ipycytoscape/cytoscape.py
> +                    counts[label] = counts.get(label, 0) + 1
This counts the number of instances that a node has a particular label (a node can have multiple labels in Neo4j). ```counts.get(label, 0)``` initializes the count with zero, and then increments the value if more of the same labels are encountered.

2021-03-30 19:54 UTC, pwrose commented
@marimeireles please go ahead and finish this PR. Let me know if you have any questions. Thanks!

2021-04-21 11:11 UTC, marimeireles approved these changes

2021-04-21 11:39 UTC, marimeireles commented
I think the neo4j example is not working anymore? @pwrose 

I can't make it work locally. It gets stuck in the following cell:
```
graph = Graph("bolt://132.249.238.185:7687", user="reader", password="demo")
```

I can't access the logs, but I suppose it's the same issue. You have any ideas of what's up with this address?

2021-04-21 23:30 UTC, pwrose commented
Our COVID-19-Net database update got stuck last night. It should work again.

From: Mariana Meireles ***@***.***>
Reply-To: QuantStack/ipycytoscape ***@***.***>
Date: Wednesday, April 21, 2021 at 4:40 AM
To: QuantStack/ipycytoscape ***@***.***>
Cc: Peter Rose ***@***.***>, Mention ***@***.***>
Subject: Re: [QuantStack/ipycytoscape] added add_graph_from_neo4j method and example notebook (#245)


I think the neo4j example is not working anymore? @pwrose<https://urldefense.com/v3/__https:/github.com/pwrose__;!!Mih3wA!WcTo10cNgjCn8saOUfodh5s2wblEcL49niIPyGF6jpwqKcIjU94rG9OX2OtWxqI$>

I can't make it work locally. It gets stuck in the following cell:

graph = Graph("bolt://132.249.238.185:7687", user="reader", password="demo")

I can't access the logs, but I suppose it's the same issue. You have any ideas of what's up with this address?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https:/github.com/QuantStack/ipycytoscape/pull/245*issuecomment-823994005__;Iw!!Mih3wA!WcTo10cNgjCn8saOUfodh5s2wblEcL49niIPyGF6jpwqKcIjU94rG9OX9zEdI6M$>, or unsubscribe<https://urldefense.com/v3/__https:/github.com/notifications/unsubscribe-auth/AA53AEBWW53R7SIRRWKX3ILTJ22R7ANCNFSM4YMAZD6A__;!!Mih3wA!WcTo10cNgjCn8saOUfodh5s2wblEcL49niIPyGF6jpwqKcIjU94rG9OXV0d3Cv8$>.

2021-04-22 09:39 UTC, marimeireles commented
Funny, now I can load the graph locally but can't query it at all, I get stuck in this cell:

```
query1 = """
MATCH p=(:City{name:'San Francisco'})-[:IN*]->(:World) RETURN p
"""
subgraph1 = graph.run(query1).to_subgraph()
```

But apparently the CI can go further? But something goes wrong on the next query, because when it tries to use the graph queried it throws a `NoneType` error.

```
widget2.graph.add_graph_from_neo4j(subgraph2)
```

I'm thinking about removing this notebook from our tests because the server seems a bit unstable, but still keep it around so people can understand how to use the `neo4j` plug.

2021-04-22 12:38 UTC, marimeireles commented
Thanks for the work @pwrose, the contribution and the patience for taking the time to create the PR and merge it :)
Really appreciated, this is a really awesome addition!

2021-04-22 12:38 UTC, merged

2021-04-22 17:27 UTC, pwrose commented
It’s a good idea to remove this notebook from the test. Our COVID database is under active development, so it’s not always available or data will be incomplete during our daily update around 7:00 – 10:00 UTC.

From: Mariana Meireles ***@***.***>
Reply-To: QuantStack/ipycytoscape ***@***.***>
Date: Thursday, April 22, 2021 at 2:39 AM
To: QuantStack/ipycytoscape ***@***.***>
Cc: Peter Rose ***@***.***>, Mention ***@***.***>
Subject: Re: [QuantStack/ipycytoscape] added add_graph_from_neo4j method and example notebook (#245)


Funny, now I can load the graph locally but can't query it at all, I get stuck in this cell:

query1 = """

MATCH p=(:City{name:'San Francisco'})-[:IN*]->(:World) RETURN p

"""

subgraph1 = graph.run(query1).to_subgraph()

But apparently the CI can go further? But something goes wrong on the next query, because when it tries to use the graph queried it throws a NoneType error.

widget2.graph.add_graph_from_neo4j(subgraph2)

I'm thinking about removing this notebook from our tests because the server seems a bit unstable, but still keep it around so people can understand how to use the neo4j plug.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https:/github.com/QuantStack/ipycytoscape/pull/245*issuecomment-824693790__;Iw!!Mih3wA!QC75OtFDPIaFV93qjSSy4EnA6Cwm9Jq5GFBeuCEl7uGcndCzxFg2UmfKD4F2of8$>, or unsubscribe<https://urldefense.com/v3/__https:/github.com/notifications/unsubscribe-auth/AA53AEEQ27UN4R3CIMUTR7DTJ7VERANCNFSM4YMAZD6A__;!!Mih3wA!QC75OtFDPIaFV93qjSSy4EnA6Cwm9Jq5GFBeuCEl7uGcndCzxFg2UmfKzJ3OIVU$>.